// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: proto/snmpv2srv.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//SNMP 叶子节点
type SnmpV2GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ips       []string          `protobuf:"bytes,1,rep,name=Ips,proto3" json:"Ips,omitempty"`
	Community string            `protobuf:"bytes,2,opt,name=Community,proto3" json:"Community,omitempty"`
	Data      map[string]string `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SnmpV2GetRequest) Reset() {
	*x = SnmpV2GetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_snmpv2srv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnmpV2GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnmpV2GetRequest) ProtoMessage() {}

func (x *SnmpV2GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snmpv2srv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnmpV2GetRequest.ProtoReflect.Descriptor instead.
func (*SnmpV2GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_snmpv2srv_proto_rawDescGZIP(), []int{0}
}

func (x *SnmpV2GetRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *SnmpV2GetRequest) GetCommunity() string {
	if x != nil {
		return x.Community
	}
	return ""
}

func (x *SnmpV2GetRequest) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

//SNMP BUlk Request
type SnmpV2BulkGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ips       []string `protobuf:"bytes,1,rep,name=Ips,proto3" json:"Ips,omitempty"`
	Community string   `protobuf:"bytes,2,opt,name=Community,proto3" json:"Community,omitempty"`
	Oids      []string `protobuf:"bytes,3,rep,name=Oids,proto3" json:"Oids,omitempty"`
}

func (x *SnmpV2BulkGetRequest) Reset() {
	*x = SnmpV2BulkGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_snmpv2srv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnmpV2BulkGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnmpV2BulkGetRequest) ProtoMessage() {}

func (x *SnmpV2BulkGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snmpv2srv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnmpV2BulkGetRequest.ProtoReflect.Descriptor instead.
func (*SnmpV2BulkGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_snmpv2srv_proto_rawDescGZIP(), []int{1}
}

func (x *SnmpV2BulkGetRequest) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *SnmpV2BulkGetRequest) GetCommunity() string {
	if x != nil {
		return x.Community
	}
	return ""
}

func (x *SnmpV2BulkGetRequest) GetOids() []string {
	if x != nil {
		return x.Oids
	}
	return nil
}

//SNMP Response
type SnmpV2Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip        string            `protobuf:"bytes,1,opt,name=Ip,proto3" json:"Ip,omitempty"`
	Community string            `protobuf:"bytes,2,opt,name=Community,proto3" json:"Community,omitempty"`
	Data      map[string]string `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Date      string            `protobuf:"bytes,4,opt,name=Date,proto3" json:"Date,omitempty"`
}

func (x *SnmpV2Result) Reset() {
	*x = SnmpV2Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_snmpv2srv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnmpV2Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnmpV2Result) ProtoMessage() {}

func (x *SnmpV2Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snmpv2srv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnmpV2Result.ProtoReflect.Descriptor instead.
func (*SnmpV2Result) Descriptor() ([]byte, []int) {
	return file_proto_snmpv2srv_proto_rawDescGZIP(), []int{2}
}

func (x *SnmpV2Result) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *SnmpV2Result) GetCommunity() string {
	if x != nil {
		return x.Community
	}
	return ""
}

func (x *SnmpV2Result) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SnmpV2Result) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type SnmpV2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result []*SnmpV2Result `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	Date   string          `protobuf:"bytes,2,opt,name=Date,proto3" json:"Date,omitempty"`
}

func (x *SnmpV2Response) Reset() {
	*x = SnmpV2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_snmpv2srv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnmpV2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnmpV2Response) ProtoMessage() {}

func (x *SnmpV2Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_snmpv2srv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnmpV2Response.ProtoReflect.Descriptor instead.
func (*SnmpV2Response) Descriptor() ([]byte, []int) {
	return file_proto_snmpv2srv_proto_rawDescGZIP(), []int{3}
}

func (x *SnmpV2Response) GetResult() []*SnmpV2Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SnmpV2Response) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

var File_proto_snmpv2srv_proto protoreflect.FileDescriptor

var file_proto_snmpv2srv_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x6e, 0x6d, 0x70, 0x76, 0x32, 0x73, 0x72,
	0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb2,
	0x01, 0x0a, 0x10, 0x53, 0x6e, 0x6d, 0x70, 0x56, 0x32, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x03, 0x49, 0x70, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69,
	0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e,
	0x69, 0x74, 0x79, 0x12, 0x35, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6e, 0x6d, 0x70, 0x56, 0x32,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x37, 0x0a, 0x09, 0x44, 0x61,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x22, 0x5a, 0x0a, 0x14, 0x53, 0x6e, 0x6d, 0x70, 0x56, 0x32, 0x42, 0x75, 0x6c,
	0x6b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x49,
	0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x49, 0x70, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x4f,
	0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x4f, 0x69, 0x64, 0x73, 0x22,
	0xbc, 0x01, 0x0a, 0x0c, 0x53, 0x6e, 0x6d, 0x70, 0x56, 0x32, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x70,
	0x12, 0x1c, 0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x12, 0x31,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6e, 0x6d, 0x70, 0x56, 0x32, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x44, 0x61, 0x74, 0x65, 0x1a, 0x37, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x51,
	0x0a, 0x0e, 0x53, 0x6e, 0x6d, 0x70, 0x56, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2b, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6e, 0x6d, 0x70, 0x56, 0x32, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x65, 0x32, 0x91, 0x01, 0x0a, 0x09, 0x53, 0x6e, 0x6d, 0x70, 0x76, 0x32, 0x73, 0x72, 0x76, 0x12,
	0x3d, 0x0a, 0x09, 0x53, 0x6e, 0x6d, 0x70, 0x56, 0x32, 0x47, 0x65, 0x74, 0x12, 0x17, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6e, 0x6d, 0x70, 0x56, 0x32, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6e,
	0x6d, 0x70, 0x56, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x45,
	0x0a, 0x0d, 0x53, 0x6e, 0x6d, 0x70, 0x56, 0x32, 0x42, 0x75, 0x6c, 0x6b, 0x47, 0x65, 0x74, 0x12,
	0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6e, 0x6d, 0x70, 0x56, 0x32, 0x42, 0x75,
	0x6c, 0x6b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6e, 0x6d, 0x70, 0x56, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_snmpv2srv_proto_rawDescOnce sync.Once
	file_proto_snmpv2srv_proto_rawDescData = file_proto_snmpv2srv_proto_rawDesc
)

func file_proto_snmpv2srv_proto_rawDescGZIP() []byte {
	file_proto_snmpv2srv_proto_rawDescOnce.Do(func() {
		file_proto_snmpv2srv_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_snmpv2srv_proto_rawDescData)
	})
	return file_proto_snmpv2srv_proto_rawDescData
}

var file_proto_snmpv2srv_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_snmpv2srv_proto_goTypes = []interface{}{
	(*SnmpV2GetRequest)(nil),     // 0: proto.SnmpV2GetRequest
	(*SnmpV2BulkGetRequest)(nil), // 1: proto.SnmpV2BulkGetRequest
	(*SnmpV2Result)(nil),         // 2: proto.SnmpV2Result
	(*SnmpV2Response)(nil),       // 3: proto.SnmpV2Response
	nil,                          // 4: proto.SnmpV2GetRequest.DataEntry
	nil,                          // 5: proto.SnmpV2Result.DataEntry
}
var file_proto_snmpv2srv_proto_depIdxs = []int32{
	4, // 0: proto.SnmpV2GetRequest.Data:type_name -> proto.SnmpV2GetRequest.DataEntry
	5, // 1: proto.SnmpV2Result.Data:type_name -> proto.SnmpV2Result.DataEntry
	2, // 2: proto.SnmpV2Response.result:type_name -> proto.SnmpV2Result
	0, // 3: proto.Snmpv2srv.SnmpV2Get:input_type -> proto.SnmpV2GetRequest
	1, // 4: proto.Snmpv2srv.SnmpV2BulkGet:input_type -> proto.SnmpV2BulkGetRequest
	3, // 5: proto.Snmpv2srv.SnmpV2Get:output_type -> proto.SnmpV2Response
	3, // 6: proto.Snmpv2srv.SnmpV2BulkGet:output_type -> proto.SnmpV2Response
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_snmpv2srv_proto_init() }
func file_proto_snmpv2srv_proto_init() {
	if File_proto_snmpv2srv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_snmpv2srv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnmpV2GetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_snmpv2srv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnmpV2BulkGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_snmpv2srv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnmpV2Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_snmpv2srv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnmpV2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_snmpv2srv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_snmpv2srv_proto_goTypes,
		DependencyIndexes: file_proto_snmpv2srv_proto_depIdxs,
		MessageInfos:      file_proto_snmpv2srv_proto_msgTypes,
	}.Build()
	File_proto_snmpv2srv_proto = out.File
	file_proto_snmpv2srv_proto_rawDesc = nil
	file_proto_snmpv2srv_proto_goTypes = nil
	file_proto_snmpv2srv_proto_depIdxs = nil
}
